import { useEffect, useMemo, useRef, useState } from 'react'
import QRCode from 'qrcode'
import { createClient, type SupabaseClient } from '@supabase/supabase-js'
import './App.css'

type Product = { id: string; name: string; price: number; stock: number; category: string; image_url?: string; flavors?: string[]; description?: string }
type Item = { productId: string; name: string; flavor?: string; quantity: number; price: number }
type Order = { id: string; order_code: string; customer_name: string; customer_phone: string; items: Item[]; total: number; payment_method: string; status: string; created_at: string }

const getDb = (): SupabaseClient | null => {
  const url = import.meta.env.VITE_SUPABASE_URL?.replace(/\/rest\/v1\/?$/, '').replace(/\/$/, '')
  const key = import.meta.env.VITE_SUPABASE_ANON_KEY
  return url?.startsWith('https://') && key ? createClient(url, key, { auth: { persistSession: false } }) : null
}
const money = (value: number) => new Intl.NumberFormat('fr-MG', { style: 'currency', currency: 'MGA', maximumFractionDigits: 0 }).format(value)
const read = <T,>(key: string, fallback: T): T => { try { return JSON.parse(localStorage.getItem(key) || '') as T } catch { return fallback } }
const mapOrder = (row: Record<string, unknown>): Order => ({ id: String(row.id), order_code: String(row.order_code ?? ''), customer_name: String(row.customer_name ?? ''), customer_phone: String(row.customer_phone ?? ''), items: Array.isArray(row.items) ? row.items as Item[] : [], total: Number(row.total ?? 0), payment_method: String(row.payment_method ?? 'cash'), status: String(row.status ?? 'pending'), created_at: String(row.created_at ?? '') })

function App() {
  const db = useMemo(getDb, [])
  const [products, setProducts] = useState<Product[]>([])
  const [orders, setOrders] = useState<Order[]>([])
  const [cart, setCart] = useState<Item[]>([])
  const [receipt, setReceipt] = useState<(Order & { qr: string }) | null>(null)
  const [receiptAnimation, setReceiptAnimation] = useState(false)
  const [admin, setAdmin] = useState(() => localStorage.getItem('fuzzy-admin') === 'true')
  const [loginOpen, setLoginOpen] = useState(false)
  const [credentials, setCredentials] = useState({ email: 'admin@fuzzy.store', password: 'admin1234' })
  const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const [payment, setPayment] = useState('cash')
  const [cartOpen, setCartOpen] = useState(false); const [lookup, setLookup] = useState(''); const [message, setMessage] = useState('')
  const video = useRef<HTMLVideoElement>(null); const stream = useRef<MediaStream | null>(null)

  useEffect(() => { localStorage.setItem('fuzzy-admin', String(admin)) }, [admin])
  useEffect(() => { const load = async () => { if (!db) return; const [{ data: ps }, { data: os }] = await Promise.all([db.from('products').select('*'), db.from('orders').select('*').order('created_at', { ascending: false })]); if (ps) setProducts(ps as Product[]); if (os) setOrders(os.map((row) => mapOrder(row as Record<string, unknown>))) }; void load() }, [db])
  useEffect(() => () => stream.current?.getTracks().forEach((track) => track.stop()), [])

  const add = (product: Product) => setCart((current) => { const found = current.find((item) => item.productId === product.id); return found ? current.map((item) => item.productId === product.id ? { ...item, quantity: Math.min(item.quantity + 1, product.stock) } : item) : [...current, { productId: product.id, name: product.name, quantity: 1, price: product.price }] })
  const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0)

  const checkout = async () => {
    if (!name.trim() || !phone.trim() || !cart.length) return setMessage('Enter your name, phone and add an item first.')
    const order: Order = { id: crypto.randomUUID(), order_code: `FU-${Math.random().toString(36).slice(2, 8).toUpperCase()}`, customer_name: name.trim(), customer_phone: phone.trim(), items: cart, total, payment_method: payment, status: 'pending', created_at: new Date().toISOString() }
    if (db) { const { error } = await db.from('orders').insert(order); if (error) return setMessage(`Order failed: ${error.message}`) }
    else { const local = read<Order[]>('fuzzy-orders', []); localStorage.setItem('fuzzy-orders', JSON.stringify([order, ...local])) }
    const qr = await QRCode.toDataURL(order.order_code, { width: 320, margin: 2 }); setReceipt({ ...order, qr }); setReceiptAnimation(true); window.setTimeout(() => setReceiptAnimation(false), 1800); setOrders((current) => [order, ...current]); setCart([]); setName(''); setPhone(''); setMessage('Order placed successfully.')
  }

  const updateStatus = async (order: Order, status: 'validated' | 'cancelled') => {
    if (!db) return setMessage('Supabase is not configured.')
    const { data, error } = await db.from('orders').update({ status }).eq('id', order.id).select('id,status').single()
    if (error || !data) return setMessage(`Database update failed: ${error?.message ?? 'order not found'}`)
    setOrders((current) => current.map((item) => item.id === order.id ? { ...item, status } : item)); setMessage(`${order.order_code}: ${status}`)
  }

  const openLookup = () => { const code = lookup.trim().split('/').filter(Boolean).pop()?.toLowerCase(); const order = orders.find((item) => item.order_code.toLowerCase() === code); setMessage(order ? `Order ${order.order_code} opened.` : 'No matching order. Enter the exact code printed below the QR.') }
  const startCamera = async () => { if (!('BarcodeDetector' in window)) return setMessage('QR camera scanning is not supported on this browser. Use the order-code field instead.'); try { stream.current = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'environment' } }); if (video.current) video.current.srcObject = stream.current; setMessage('Camera opened. Point it at the order QR code.') } catch { setMessage('Camera permission was denied. Use the order-code field instead.') } }
  const login = (event: React.FormEvent) => { event.preventDefault(); const email = import.meta.env.VITE_ADMIN_EMAIL ?? 'admin@fuzzy.store'; const password = import.meta.env.VITE_ADMIN_PASSWORD ?? 'admin1234'; if (credentials.email === email && credentials.password === password) { setAdmin(true); setLoginOpen(false); setReceipt(null) } else setMessage('Incorrect admin credentials.') }
  const download = () => { if (!receipt) return; const link = document.createElement('a'); link.href = receipt.qr; link.download = `${receipt.order_code}-receipt.png`; link.click() }

  if (admin) return <Admin orders={orders} lookup={lookup} setLookup={setLookup} openLookup={openLookup} startCamera={startCamera} video={video} updateStatus={updateStatus} logout={() => setAdmin(false)} message={message} />
  return <>
    <style>{styles}</style><div className="app-shell customer-shell"><header className="topbar"><div className="brand-block"><div className="brand-mark">FS</div><div><div className="brand-name">Fuzzy Store</div><div className="brand-tag">Imported snacks & spirits</div></div></div><button className="secondary-button" onClick={() => setLoginOpen(true)}>Admin Login</button><button className="cart-button" onClick={() => setCartOpen(true)}>Cart ({cart.reduce((sum, item) => sum + item.quantity, 0)})</button></header>
      <main className="page-shell"><section className="hero-section new-hero"><div><span className="eyebrow">A little joy, delivered</span><h1>Good snacks. Great moments.</h1><p>Explore imported favourites, fresh drinks and late-night treats selected by Fuzzy Store.</p><button className="primary-button" onClick={() => document.getElementById('collection')?.scrollIntoView({ behavior: 'smooth' })}>Explore collection</button></div><div className="hero-visual"><div className="lemur">◕ᴥ◕</div><strong>Fresh picks<br />for every mood</strong></div></section><section id="collection" className="content-grid"><div className="product-panel"><div className="section-header"><h2>Featured collection</h2><span>{products.length} items</span></div><div className="product-grid">{products.map((product) => <article className="product-card" key={product.id}><div className="product-image-wrap"><img src={product.image_url || 'https://placehold.co/600x400/2f1c2e/efe5d0?text=Fuzzy+Store'} alt={product.name} /><span className="stock-pill">{product.stock} left</span></div><div className="product-body"><span className="category-badge">{product.category}</span><h3>{product.name}</h3><p>{product.description}</p><strong className="price">{money(product.price)}</strong><button className="primary-button full-width" disabled={!product.stock} onClick={() => add(product)}>{product.stock ? 'Add to cart' : 'Out of stock'}</button></div></article>)}</div></div></section></main>
      {cartOpen && <aside className="cart-panel mobile-cart"><div className="cart-header"><h2>Your cart</h2><button className="ghost-button" onClick={() => setCartOpen(false)}>Close</button></div>{cart.map((item) => <div className="cart-item" key={item.productId}><span>{item.name} × {item.quantity}</span><strong>{money(item.price * item.quantity)}</strong></div>)}<div className="totals-box"><strong>Total {money(total)}</strong></div><input placeholder="Your name" value={name} onChange={(event) => setName(event.target.value)} /><input placeholder="Phone" value={phone} onChange={(event) => setPhone(event.target.value)} /><select value={payment} onChange={(event) => setPayment(event.target.value)}><option value="cash">Cash</option><option value="mvola">Mvola</option><option value="card">Card</option></select><button className="primary-button full-width" onClick={() => void checkout()}>Place order</button></aside>}
      {loginOpen && <div className="modal-backdrop"><form className="panel admin-signin" onSubmit={login}><button type="button" className="ghost-button" onClick={() => setLoginOpen(false)}>Close</button><h2>Admin access</h2><input value={credentials.email} onChange={(event) => setCredentials({ ...credentials, email: event.target.value })} /><input type="password" value={credentials.password} onChange={(event) => setCredentials({ ...credentials, password: event.target.value })} /><button className="primary-button">Open dashboard</button></form></div>}
      {receipt && <section className={`receipt-panel panel ${receiptAnimation ? 'receipt-arriving' : ''}`}><div className="receipt-box"><div className="receipt-printer">🦝 <span>printing...</span></div><h2>Order confirmed</h2><p>{receipt.order_code} · {receipt.customer_name}</p>{receipt.items.map((item) => <div className="receipt-item" key={item.productId}><span>{item.name} × {item.quantity}</span><strong>{money(item.price * item.quantity)}</strong></div>)}<div className="receipt-total"><strong>Total</strong><strong>{money(receipt.total)}</strong></div><img className="receipt-qr" src={receipt.qr} alt="Order QR code" /><button className="primary-button full-width" onClick={download}>Download receipt</button><button className="ghost-button full-width" onClick={() => setReceipt(null)}>Continue shopping</button></div></section>}{message && <div className="toast info">{message}</div>}</div></>
}

function Admin({ orders, lookup, setLookup, openLookup, startCamera, video, updateStatus, logout, message }: { orders: Order[]; lookup: string; setLookup: (value: string) => void; openLookup: () => void; startCamera: () => void; video: React.RefObject<HTMLVideoElement | null>; updateStatus: (order: Order, status: 'validated' | 'cancelled') => Promise<void>; logout: () => void; message: string }) { return <><style>{adminStyles}</style><div className="admin-shell"><header className="admin-header"><div><small>FUZZY STORE / OPERATIONS</small><h1>Order control center</h1><p>Manage live orders and update their status.</p></div><button className="admin-secondary" onClick={logout}>Exit admin</button></header><main className="admin-content"><section className="admin-tools"><h2>Receipt scanner</h2><div className="manual-lookup"><input value={lookup} onChange={(event) => setLookup(event.target.value)} placeholder="Order code, e.g. FU-ABC123" /><button className="admin-primary" onClick={openLookup}>Open order</button><button className="admin-secondary" onClick={startCamera}>Open camera</button></div><video className="admin-video" ref={video} muted playsInline /></section><section className="admin-orders"><div className="admin-filter-title"><h2>Orders</h2><span>{orders.length} total</span></div>{orders.map((order) => <article className="admin-order" key={order.id}><div><strong>{order.order_code}</strong><span>{order.customer_name} · {order.customer_phone}</span></div><b className={`admin-status ${order.status}`}>{order.status}</b><small>{money(order.total)} · {new Date(order.created_at).toLocaleString()}</small><div className="admin-actions"><button className="admin-primary" disabled={order.status === 'validated'} onClick={() => void updateStatus(order, 'validated')}>Validate</button><button className="admin-danger" disabled={order.status === 'cancelled'} onClick={() => void updateStatus(order, 'cancelled')}>Cancel</button></div></article>)}</section></main>{message && <div className="admin-message">{message}</div>}</div></> }

const styles = `
.new-hero{align-items:center}.hero-visual{min-height:260px;border-radius:26px;background:radial-gradient(circle at 50% 30%,#b45b53,transparent 28%),linear-gradient(145deg,#391d2a,#17151b);display:grid;place-items:center;color:#f7d9a5;text-align:center;font-size:1.2rem}.lemur{font-size:5rem;color:#f4d29a;animation:float 3s ease-in-out infinite}.receipt-printer{text-align:center;font-size:2rem;animation:print 1.8s ease-in-out}.receipt-printer span{display:block;font-size:.8rem;color:#8a6f61}.receipt-qr{display:block;width:180px;height:180px;margin:18px auto}.receipt-arriving{animation:receiptIn .6s ease-out}@keyframes float{50%{transform:translateY(-10px) rotate(3deg)}}@keyframes print{0%{transform:translateY(-25px);opacity:0}45%{transform:translateY(0);opacity:1}70%{transform:translateY(4px)}100%{transform:translateY(0)}}@keyframes receiptIn{from{opacity:0;transform:translateY(22px) scale(.97)}to{opacity:1;transform:none}}.modal-backdrop{position:fixed;inset:0;z-index:20;display:grid;place-items:center;background:#100a0dcc;padding:18px}.mobile-cart{position:fixed;z-index:15;right:16px;top:80px;width:min(420px,calc(100% - 32px));max-height:calc(100vh - 96px);overflow:auto;background:#21161d;border:1px solid #754b50;border-radius:22px;padding:18px;box-shadow:0 20px 70px #0008}.mobile-cart input,.mobile-cart select{width:100%;margin-top:10px;padding:12px;border-radius:10px;border:1px solid #6b4b50;background:#2d1e26;color:white}@media(max-width:680px){.customer-shell{padding:10px 10px 40px}.topbar{position:sticky;top:8px;padding:12px;gap:10px}.brand-tag{display:none}.new-hero{padding:24px 18px}.new-hero h1{font-size:2.5rem}.hero-visual{min-height:180px}.category-nav{display:none}.product-grid{grid-template-columns:1fr}.product-image-wrap{height:180px}.cart-button,.secondary-button,.primary-button{min-height:44px}.receipt-box{padding:18px}.receipt-panel{margin:14px 0}}
`
const adminStyles = `.admin-shell{min-height:100vh;background:#f4f7fb;color:#1b2638;padding:clamp(18px,4vw,48px)}.admin-header,.admin-content{max-width:1100px;margin:auto}.admin-header{display:flex;justify-content:space-between;align-items:start;gap:20px}.admin-header small{color:#60708a;letter-spacing:.12em}.admin-header h1{font-size:clamp(2rem,5vw,3.5rem);margin:8px 0}.admin-header p{color:#60708a}.admin-content{display:grid;gap:20px;margin-top:30px}.admin-tools,.admin-orders{background:white;border:1px solid #dce3ed;border-radius:18px;padding:22px;box-shadow:0 10px 30px #27364d0d}.manual-lookup{display:flex;gap:10px;flex-wrap:wrap}.manual-lookup input{flex:1;min-width:200px;padding:13px;border:1px solid #ccd6e3;border-radius:10px}.admin-primary,.admin-secondary,.admin-danger{border:0;border-radius:10px;padding:12px 16px;cursor:pointer;font-weight:700}.admin-primary{background:#2457d6;color:white}.admin-secondary{background:#e8edf5;color:#26344b}.admin-danger{background:#ffe7e8;color:#bd2631}.admin-video{width:100%;max-height:280px;margin-top:16px;border-radius:12px;background:#111}.admin-filter-title,.admin-order{display:flex;align-items:center;gap:14px}.admin-filter-title{justify-content:space-between}.admin-order{flex-wrap:wrap;border-top:1px solid #e5eaf1;padding:17px 0}.admin-order>div:first-child{display:grid;min-width:210px;flex:1}.admin-order span,.admin-order small{color:#66758b}.admin-status{padding:6px 10px;border-radius:99px;font-size:.8rem}.admin-status.pending{background:#fff1d3;color:#976300}.admin-status.validated{background:#dcf7e7;color:#177342}.admin-status.cancelled{background:#ffe1e3;color:#b3212a}.admin-actions{display:flex;gap:8px}.admin-message{position:fixed;bottom:18px;right:18px;background:#1d2d46;color:white;padding:14px 18px;border-radius:10px}@media(max-width:600px){.admin-shell{padding:14px}.admin-header{display:block}.admin-header button{margin-top:12px;width:100%}.admin-order{display:grid}.admin-actions button{flex:1}}
`

export default App
